site_name: Pyxy3D
site_description: A brief description of your project
site_url: https://mprib.github.io/pyxy3d/
repo_url: https://github.com/mprib/pyxy3d
repo_name: pyxy3d

theme:
  logo: images/pyxy3d_logo.svg
  favicon: images/pyxy3d_logo.svg
  name: material
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: green
    - media: "(prefers-color-scheme: light)"
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue 
      accent: green


nav:
  - Home: home.md
  - FAQ: faq.md
  - Getting Started:
      - Requirements: requirements.md
      - Installation: installation.md
  - Reference:
      - Code Map: project_structure.md
      - Docs: doc_notes.md
  - License: LICENSE.md

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
copyright: |
  &copy; 2023 <a href="https://github.com/mprib"  target="_blank" rel="noopener">Mac Prible</a>